version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.4.0
  gitleaks: upenn-libraries/gitleaks@dev:alpha

workflows:
  test_and_publish:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/test-in-builds:
          attach-workspace: true
          orb-name: gitleaks
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: .circleci/test.yml
          requires:
            - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: upenn-libraries/gitleaks
          requires:
            - orb-tools/test-in-builds
