description: |
  Use Gitleaks to clone a remote repository and then check the local repository
  with the provided configuration options. This example will redact secrets
  from the build output, use the .gitleaks.toml file in the repository to
  configure Gitleaks, and use the provided Gitleaks Docker image.

usage:
  version: 2.1

  orbs:
    gitleaks: upenn-libraries/gitleaks@0.1.0

    workflows:
      check_for_secrets:
        jobs:
          - gitleaks/check_local:
              image: quay.io/upennlibraries/gitleaks:v1.23.0
              options: --redact --repo-config
